<a href="https://colab.research.google.com/github/AhmetBugraKaplan/NumpyDersleri/blob/main/NumpyDerlseri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

# 2- Numpy ile Nokta Doğru ve Uzay


In [58]:
skaler = np.array(90)
print(skaler)

90


In [53]:
vektor = np.array([1,2,3,4,5,6])
print(vektor)

[1 2 3 4 5 6]


In [54]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
tensor = np.array([[[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]]]


# 3-Neden Numpy

In [13]:
import time

In [14]:
z1 = time.time()

liste = []
for a in range (1000000):
  kuvvet = a**100
  liste.append(kuvvet)



z2 = time.time()

print(z2-z1)

1.1204612255096436


In [15]:
z3 = time.time()

liste2 = np.arange(1000000)**100


z4 = time.time()

print(z4-z3)

0.006917476654052734


#Ders 3 Index ve Slice

In [16]:
vektor = np.array([0,2,4,5,6,7,8,15])

In [17]:
print(vektor[3])

5


In [18]:
print(vektor[1:3])

[2 4]


In [19]:
print(vektor[:2])

[0 2]


In [20]:
print(vektor[0:12:2])

[0 4 6 8]


#Ders 4 Size,Shape,Dtype,ndim


In [21]:
  vektor = np.array([1,2,3,4,5,6])
  print(vektor)


  print("")
  matris= np.array([[1,2,3],[4,5,6],[7,8,9]])
  print(matris)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(vektor.size)
print(matris.size)

6
9


In [23]:
vektor.shape

(6,)

In [24]:
matris.shape

(3, 3)

In [25]:
vektor.ndim

1

In [26]:
matris.ndim

2

# Ders6- Numpy Veri Tipi Değiştirme

In [27]:
sayilar = np.array([1,2,3,4,5,6])

In [28]:
sayilar.dtype

dtype('int64')

In [29]:
sayilar = sayilar.astype("int8")
sayilar.dtype

dtype('int8')

In [30]:
sayilar = np.array([1,2,3,4,5,6],dtype="int8")
sayilar.dtype

dtype('int8')

# Ders7- Matrislerde Slice

In [31]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [32]:
matris

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
matris[0]

array([1, 2, 3])

In [34]:
matris[2]

array([7, 8, 9])

In [35]:
matris[1:2]

array([[4, 5, 6]])

In [36]:
matris[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [37]:
matris[0:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
matris[:5]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
matris[:4]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
matris[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
matris[0:4,0:1]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

#Ders 8 - Random Matris Oluşturma

In [42]:
np.random.randint(0,99,(4,4))


array([[32, 98, 25, 48],
       [32, 35, 49, 76],
       [ 1, 68, 88,  6],
       [83,  6, 76, 57]])

#Ders 9 - Arange ile Vektör Oluşturma


In [61]:
liste = [1,2,3,4,5,6]
range(1_000_000)

range(0, 1000000)

In [44]:
milyon = np.arange(1000000)

In [45]:
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [48]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

#Ders 10-linspace() ile vektör oluşturma

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [51]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

#Ders 11 Numpy ile Yeniden Boyutlandırma reshape() ile



In [67]:
ml = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(ml)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
ml.shape

(3, 4)

In [72]:
ml.size

12

In [78]:
ml.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
np.random.randint(0,2,(8,6)).reshape(4,12)

array([[1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0]])

#Ders 12 copy ve View() Metotları

In [86]:
matris = np.random.randint(0,5,(4,4))

In [87]:
matris

array([[2, 2, 3, 0],
       [3, 2, 0, 3],
       [0, 4, 4, 4],
       [2, 2, 4, 2]])

In [91]:
matris2 = matris.view()
matris2

array([[2, 2, 3, 0],
       [3, 2, 0, 3],
       [0, 4, 4, 4],
       [2, 2, 4, 2]])

In [93]:
matris2[0]=[9,9,9,9]
matris2

array([[9, 9, 9, 9],
       [3, 2, 0, 3],
       [0, 4, 4, 4],
       [2, 2, 4, 2]])

In [94]:
matris

array([[9, 9, 9, 9],
       [3, 2, 0, 3],
       [0, 4, 4, 4],
       [2, 2, 4, 2]])

In [97]:
matris3 = np.random.randint(0,5,(4,4))
matris3

array([[0, 3, 3, 0],
       [2, 2, 3, 0],
       [0, 4, 3, 0],
       [0, 2, 0, 0]])

In [99]:
matris4=matris3.copy()
matris4

array([[0, 3, 3, 0],
       [2, 2, 3, 0],
       [0, 4, 3, 0],
       [0, 2, 0, 0]])

In [100]:
matris4[0]

array([0, 3, 3, 0])

In [101]:
matris4[0] = [3,1,3,1]
matris4

array([[3, 1, 3, 1],
       [2, 2, 3, 0],
       [0, 4, 3, 0],
       [0, 2, 0, 0]])

In [102]:
matris3

array([[0, 3, 3, 0],
       [2, 2, 3, 0],
       [0, 4, 3, 0],
       [0, 2, 0, 0]])

**Yani view ile kopyalarsak ilgili değişkenlerde değişir.**



**Fakat copy ile kopyalarsak diğerlerini alakadar etmez**

#Ders13 - ones zeros full ile  matris oluşturma

In [103]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [104]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [106]:
np.ones(shape=(7,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [109]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])