<a href="https://colab.research.google.com/github/AhmetBugraKaplan/NumpyDersleri/blob/main/NumpyDerlseri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

# 2- Numpy ile Nokta Doğru ve Uzay


In [ ]:
skaler = np.array(90)

In [ ]:
vektor = np.array([1,2,3,4,5,6])
print(vektor)

[1 2 3 4 5 6]


In [ ]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
tensor = np.array([[[1,2,3],[4,5,6]]])

# 3-Neden Numpy

In [ ]:
import time

In [ ]:
z1 = time.time()

liste = []
for a in range (1000000):
  kuvvet = a**100
  liste.append(kuvvet)



z2 = time.time()

print(z2-z1)

1.5836591720581055


In [ ]:
z3 = time.time()

liste2 = np.arange(1000000)**100


z4 = time.time()

print(z4-z3)

0.015042781829833984


#Ders 3 Index ve Slice

In [ ]:
vektor = np.array([0,2,4,5,6,7,8,15])

In [ ]:
print(vektor[3])

5


In [ ]:
print(vektor[1:3])

[2 4]


In [ ]:
print(vektor[:2])

[0 2]


In [ ]:
print(vektor[0:12:2])

[0 4 6 8]


#Ders 4 Size,Shape,Dtype,ndim


In [ ]:
  vektor = np.array([1,2,3,4,5,6])
  print(vektor)


  print("")
  matris= np.array([[1,2,3],[4,5,6],[7,8,9]])
  print(matris)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(vektor.size)
print(matris.size)

6
9


In [ ]:
vektor.shape

(6,)

In [ ]:
matris.shape

(3, 3)

In [ ]:
vektor.ndim

1

In [ ]:
matris.ndim

2

# Ders6- Numpy Veri Tipi Değiştirme

In [ ]:
sayilar = np.array([1,2,3,4,5,6])

In [ ]:
sayilar.dtype

dtype('int64')

In [ ]:
sayilar = sayilar.astype("int8")
sayilar.dtype

dtype('int8')

In [ ]:
sayilar = np.array([1,2,3,4,5,6],dtype="int8")
sayilar.dtype

dtype('int8')

# Ders7- Matrislerde Slice

In [ ]:
matris = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
matris

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
matris[0]

array([1, 2, 3])

In [ ]:
matris[2]

array([7, 8, 9])

In [ ]:
matris[1:2]

array([[4, 5, 6]])

In [ ]:
matris[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matris[0:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
matris[:5]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
matris[:4]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
matris[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matris[0:4,0:1]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

#Ders 8 - Random Matris Oluşturma

In [ ]:
np.random.randint(0,99,(4,4))


array([[ 7, 70,  2, 91],
       [47, 36, 12, 68],
       [45, 36, 60, 87],
       [74, 64, 42,  4]])

#Ders 9 - Arange ile Vektör Oluşturma


In [ ]:
liste = [1,2,3,4,5,6]
range(1_000_000)

range(0, 1000000)

In [ ]:
milyon = np.arange(1000000)

In [ ]:
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

#Ders 10-linspace() ile vektör oluşturma

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])